# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128)),
                ('first_name', models.CharField(default=None, max_length=128)),
                ('last_name', models.CharField(default=None, max_length=128)),
                ('email', models.CharField(default=None, max_length=128, unique=True)),
                ('phone', models.CharField(default=None, max_length=24)),
                ('message', models.TextField(default=None)),
            ],
        ),
    ]
